container: docker.io/rpavlyuk/c7-lifesospy_mqtt
created: 2019-08-12 11:53:53.501852
name: lifesospy_mqtt
ports: {}
volumes:
        /usr/share/lifesospy_mqtt:
                bind: /lifesospy_mqtt
                mode: rw
        /etc/localtime:
                bind: /etc/localtime
                mode: ro
        /var/log/lifesospy_mqtt/journal:
                bind: /var/log/journal
                mode: rw
privileged: false
tty: true
environment: {}
network_mode: bridge
working_dir: /root
command:
        host:
                post: docker exec lifesospy_mqtt journalctl --flush
