
# Settings for the LifeSOS interface
lifesos:

  # Host and Port for the LifeSOS TCP Server to connect as a client,
  # or Port only to listen as a server for the LifeSOS TCP Client
  host: 192.168.1.220
  port: 1681
  
  # Master password, if needed by network interface
  password: ''

# Settings for the MQTT client
mqtt:

  # URI providing the details needed to connect to the MQTT broker
  # Refer https://github.com/mqtt/mqtt.github.io/wiki/URI-Scheme
  uri: mqtt://192.168.1.7:1883
  
  # Unique client identifier; no need to change unless running multiple instances
  client_id: lifesos

# Settings for the translator between LifeSOS and MQTT
translator:

  # To automatically configure devices in Home Assistant, ensure this line
  # matches the setting in Home Assistant's config file. Note any devices and
  # switches will need to be assigned a 'ha_name"' to be exported.
  # Refer https://www.home-assistant.io/docs/mqtt/discovery/
  ha_discovery_prefix: homeassistant
  
  # Topic and Payload to announce Home Assistant has come online. When received,
  # our MQTT client will send out the device configurations for discovery.
  ha_birth_topic: homeassistant/status
  ha_birth_payload: online

  # Provide a topic for the Base Unit here
  baseunit:
    topic: home/alarm
    ha_name: "LifeSOS"
  
  # List your enrolled devices here and provide a topic
  # Hint: Run with '-e' option to get a list of device ids
  devices:
    #- device_id: '012cba'
    #  topic: home/remote
    #- device_id: '345def'
    #  topic: home/front/door
    #  ha_name: "Front Door"
    #  ha_name_rssi: "Front Door RSSI"
    #- device_id: '123abc'
    #  topic: home/lounge/motion
    #  auto_reset_interval: 180
    #  ha_name: "Lounge Motion"
    #  ha_name_rssi: "Lounge Motion RSSI"
    - device_id: '6d8b06'
      topic: home/security/controller_01
      ha_name: "Remote Controller 01-01"
      ha_name_rssi: "Remote Controller 01-01"
    - device_id: 'fd8906'
      topic: home/security/controller_02
      ha_name: "Remote Controller 01-02"
      ha_name_rssi: "Remote Controller 01-02"
    - device_id: '4d0407'
      topic: home/security/controller_03
      ha_name: "Remote Controller 01-03"
      ha_name_rssi: "Remote Controller 01-03"
    - device_id: '009929'
      topic: home/security/door_03_01
      ha_name: "Main Entrance Doors"
      ha_name_rssi: "Main Entrance Doors"
  
  # Uncomment any switches you own and provide a topic
  switches:
    #- switch_number: 1
    #  topic: home/lounge/heater
    #  ha_name: "Lounge Heater"
    #- switch_number: 2
    #  topic: home/room/switch02
    #- switch_number: 3
    #  topic: home/room/switch03
    #- switch_number: 4
    #  topic: home/room/switch04
    #- switch_number: 5
    #  topic: home/room/switch05
    #- switch_number: 6
    #  topic: home/room/switch06
    #- switch_number: 7
    #  topic: home/room/switch07
    #- switch_number: 8
    #  topic: home/room/switch08
    #- switch_number: 9
    #  topic: home/room/switch09
    #- switch_number: 10
    #  topic: home/room/switch10
    #- switch_number: 11
    #  topic: home/room/switch11
    #- switch_number: 12
    #  topic: home/room/switch12
    #- switch_number: 13
    #  topic: home/room/switch13
    #- switch_number: 14
    #  topic: home/room/switch14
    #- switch_number: 15
    #  topic: home/room/switch15
    #- switch_number: 16
    #  topic: home/room/switch16

# Settings to configure logging
# Valid severity levels are:
# critical, error, warning, info, debug
logger:

  default: info
  
  #namespaces:
  #  lifesospy: debug
  #  lifesospy_mqtt: debug
  #  paho.mqtt: debug
